In [15]:
import numpy as np

In [16]:
one_d_array = np.array([1, 2, 3])
print(one_d_array)
one_d_array.shape

[1 2 3]


(3,)

In [17]:
two_d_array = np.array([[ 1, 2, 3], [4, 5, 6]])
print(two_d_array)
two_d_array.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [20]:
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_d_array)
three_d_array.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [37]:
#subset

print(one_d_array[1])

print(two_d_array[0, 1])

print(three_d_array[0, 0, 1])

2
2
2


In [45]:
#slicing

print(one_d_array[0 : -1])

print(two_d_array[: 1, 0 : -1])

print(three_d_array[: 1, : 1, 0 : -1])


[1 2]
[[1 2]]
[[[1 2]]]


In [18]:
#%reset